package com.znblog.model;

import com.znblog.model.base.BaseLessonsPlan;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LessonsPlan extends BaseLessonsPlan<LessonsPlan> {
	public static final LessonsPlan dao = new LessonsPlan();
}
