package com.znblog.model;

import com.znblog.model.base.BaseLessonEval;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LessonEval extends BaseLessonEval<LessonEval> {
	public static final LessonEval dao = new LessonEval();
}
