package com.znblog.model;

import com.znblog.model.base.BaseLessons;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Lessons extends BaseLessons<Lessons> {
	public static final Lessons dao = new Lessons();
}
