package com.znblog.model;

import com.znblog.model.base.BaseLessonsType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LessonsType extends BaseLessonsType<LessonsType> {
	public static final LessonsType dao = new LessonsType();
}
