package com.znblog.model;

import com.znblog.model.base.BaseZnArticle;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZnArticle extends BaseZnArticle<ZnArticle> {
	public static final ZnArticle dao = new ZnArticle();
}
