package com.znblog.model;

import com.znblog.model.base.BaseZnDiscuss;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZnDiscuss extends BaseZnDiscuss<ZnDiscuss> {
	public static final ZnDiscuss dao = new ZnDiscuss();
}
