package com.znblog.model;

import com.znblog.model.base.BaseZnJudge;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZnJudge extends BaseZnJudge<ZnJudge> {
	public static final ZnJudge dao = new ZnJudge();
}
