package com.znblog.model;

import com.znblog.model.base.BaseZnUserBase;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZnUserBase extends BaseZnUserBase<ZnUserBase> {
	public static final ZnUserBase dao = new ZnUserBase();
}
