package com.znblog.model;

import com.znblog.model.base.BaseZnWeeklyReport;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZnWeeklyReport extends BaseZnWeeklyReport<ZnWeeklyReport> {
	public static final ZnWeeklyReport dao = new ZnWeeklyReport();
}
