package com.znblog.model;

import com.znblog.model.base.BaseZnWeekreports;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZnWeekreports extends BaseZnWeekreports<ZnWeekreports> {
	public static final ZnWeekreports dao = new ZnWeekreports();
}
