package com.znblog.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLessons<M extends BaseLessons<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setLessonName(java.lang.String lessonName) {
		set("lesson_name", lessonName);
	}

	public java.lang.String getLessonName() {
		return get("lesson_name");
	}

	public void setLessonType(java.lang.String lessonType) {
		set("lesson_type", lessonType);
	}

	public java.lang.String getLessonType() {
		return get("lesson_type");
	}

	public void setLessonDes(java.lang.String lessonDes) {
		set("lesson_des", lessonDes);
	}

	public java.lang.String getLessonDes() {
		return get("lesson_des");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setIsCycle(java.lang.String isCycle) {
		set("is_cycle", isCycle);
	}

	public java.lang.String getIsCycle() {
		return get("is_cycle");
	}

	public void setState(java.lang.String state) {
		set("state", state);
	}

	public java.lang.String getState() {
		return get("state");
	}

	public void setNotes(java.lang.String notes) {
		set("notes", notes);
	}

	public java.lang.String getNotes() {
		return get("notes");
	}

}
