package com.znblog.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseZnArticle<M extends BaseZnArticle<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setPcategory(java.lang.Long Pcategory) {
		set("Pcategory", Pcategory);
	}

	public java.lang.Long getPcategory() {
		return get("Pcategory");
	}

	public void setCategory(java.lang.Long category) {
		set("category", category);
	}

	public java.lang.Long getCategory() {
		return get("category");
	}

	public void setImgUrl(java.lang.String imgUrl) {
		set("imgUrl", imgUrl);
	}

	public java.lang.String getImgUrl() {
		return get("imgUrl");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public void setSecondTitle(java.lang.String secondTitle) {
		set("secondTitle", secondTitle);
	}

	public java.lang.String getSecondTitle() {
		return get("secondTitle");
	}

	public void setSummary(java.lang.String summary) {
		set("summary", summary);
	}

	public java.lang.String getSummary() {
		return get("summary");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public void setPostTime(java.util.Date postTime) {
		set("postTime", postTime);
	}

	public java.util.Date getPostTime() {
		return get("postTime");
	}

	public void setAuthor(java.lang.String author) {
		set("author", author);
	}

	public java.lang.String getAuthor() {
		return get("author");
	}

	public void setCommentCount(java.lang.Long commentCount) {
		set("commentCount", commentCount);
	}

	public java.lang.Long getCommentCount() {
		return get("commentCount");
	}

	public void setReadCount(java.lang.Long readCount) {
		set("readCount", readCount);
	}

	public java.lang.Long getReadCount() {
		return get("readCount");
	}

	public void setSmCount(java.lang.Integer smCount) {
		set("smCount", smCount);
	}

	public java.lang.Integer getSmCount() {
		return get("smCount");
	}

	public void setLastUpdateTime(java.util.Date lastUpdateTime) {
		set("lastUpdateTime", lastUpdateTime);
	}

	public java.util.Date getLastUpdateTime() {
		return get("lastUpdateTime");
	}

	public void setAccountId(java.lang.Integer accountId) {
		set("accountId", accountId);
	}

	public java.lang.Integer getAccountId() {
		return get("accountId");
	}

	public void setAccountName(java.lang.String accountName) {
		set("accountName", accountName);
	}

	public java.lang.String getAccountName() {
		return get("accountName");
	}

	public void setLastAccountId(java.lang.Integer lastAccountId) {
		set("lastAccountId", lastAccountId);
	}

	public java.lang.Integer getLastAccountId() {
		return get("lastAccountId");
	}

	public void setLastAccountName(java.lang.String lastAccountName) {
		set("lastAccountName", lastAccountName);
	}

	public java.lang.String getLastAccountName() {
		return get("lastAccountName");
	}

	public void setRelPersonId(java.lang.Integer relPersonId) {
		set("relPersonId", relPersonId);
	}

	public java.lang.Integer getRelPersonId() {
		return get("relPersonId");
	}

	public void setRelPersonName(java.lang.String relPersonName) {
		set("relPersonName", relPersonName);
	}

	public java.lang.String getRelPersonName() {
		return get("relPersonName");
	}

	public void setRelCompanyId(java.lang.Integer relCompanyId) {
		set("relCompanyId", relCompanyId);
	}

	public java.lang.Integer getRelCompanyId() {
		return get("relCompanyId");
	}

	public void setRelCompanyName(java.lang.String relCompanyName) {
		set("relCompanyName", relCompanyName);
	}

	public java.lang.String getRelCompanyName() {
		return get("relCompanyName");
	}

	public void setNotes(java.lang.String notes) {
		set("notes", notes);
	}

	public java.lang.String getNotes() {
		return get("notes");
	}

}
