package com.znblog.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseZnNotsubmitted<M extends BaseZnNotsubmitted<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setNotsubmittedUsername(java.lang.String notsubmittedUsername) {
		set("notsubmitted_username", notsubmittedUsername);
	}

	public java.lang.String getNotsubmittedUsername() {
		return get("notsubmitted_username");
	}

	public void setNotsubmittedTime(java.util.Date notsubmittedTime) {
		set("notsubmitted_time", notsubmittedTime);
	}

	public java.util.Date getNotsubmittedTime() {
		return get("notsubmitted_time");
	}

}
