package com.znblog.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLessonEval<M extends BaseLessonEval<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setLessonPlanId(java.lang.Integer lessonPlanId) {
		set("lesson_plan_id", lessonPlanId);
	}

	public java.lang.Integer getLessonPlanId() {
		return get("lesson_plan_id");
	}

	public void setEvalDes(java.lang.String evalDes) {
		set("eval_des", evalDes);
	}

	public java.lang.String getEvalDes() {
		return get("eval_des");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setState(java.lang.String state) {
		set("state", state);
	}

	public java.lang.String getState() {
		return get("state");
	}

}
