package com.znblog.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseZnWeekreports<M extends BaseZnWeekreports<M>> extends Model<M> implements IBean {

	public void setID(java.lang.Integer ID) {
		set("ID", ID);
	}

	public java.lang.Integer getID() {
		return get("ID");
	}

	public void setReporterWriter(java.lang.String reporterWriter) {
		set("reporter_writer", reporterWriter);
	}

	public java.lang.String getReporterWriter() {
		return get("reporter_writer");
	}

	public void setReporterThisweek(java.lang.String reporterThisweek) {
		set("reporter_thisweek", reporterThisweek);
	}

	public java.lang.String getReporterThisweek() {
		return get("reporter_thisweek");
	}

	public void setReporterNextweek(java.lang.String reporterNextweek) {
		set("reporter_nextweek", reporterNextweek);
	}

	public java.lang.String getReporterNextweek() {
		return get("reporter_nextweek");
	}

	public void setReporterDifficulty(java.lang.String reporterDifficulty) {
		set("reporter_difficulty", reporterDifficulty);
	}

	public java.lang.String getReporterDifficulty() {
		return get("reporter_difficulty");
	}

	public void setReporterTime(java.util.Date reporterTime) {
		set("reporter_time", reporterTime);
	}

	public java.util.Date getReporterTime() {
		return get("reporter_time");
	}

}
