package com.znblog.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseZnComment<M extends BaseZnComment<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public void setAccountId(java.lang.Long accountId) {
		set("accountId", accountId);
	}

	public java.lang.Long getAccountId() {
		return get("accountId");
	}

	public void setAccountName(java.lang.String accountName) {
		set("accountName", accountName);
	}

	public java.lang.String getAccountName() {
		return get("accountName");
	}

	public void setPostTime(java.util.Date postTime) {
		set("postTime", postTime);
	}

	public java.util.Date getPostTime() {
		return get("postTime");
	}

	public void setArticleId(java.lang.Integer articleId) {
		set("articleId", articleId);
	}

	public java.lang.Integer getArticleId() {
		return get("articleId");
	}

	public void setForId(java.lang.Integer forId) {
		set("forId", forId);
	}

	public java.lang.Integer getForId() {
		return get("forId");
	}

	public void setNotes(java.lang.String notes) {
		set("notes", notes);
	}

	public java.lang.String getNotes() {
		return get("notes");
	}

}
