package com.znblog.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserBase<M extends BaseUserBase<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setUserName(java.lang.String userName) {
		set("user_name", userName);
	}

	public java.lang.String getUserName() {
		return get("user_name");
	}

	public void setUserPwd(java.lang.String userPwd) {
		set("user_pwd", userPwd);
	}

	public java.lang.String getUserPwd() {
		return get("user_pwd");
	}

	public void setSex(java.lang.String sex) {
		set("sex", sex);
	}

	public java.lang.String getSex() {
		return get("sex");
	}

	public void setBirthday(java.util.Date birthday) {
		set("birthday", birthday);
	}

	public java.util.Date getBirthday() {
		return get("birthday");
	}

	public void setIntroduce(java.lang.String introduce) {
		set("introduce", introduce);
	}

	public java.lang.String getIntroduce() {
		return get("introduce");
	}

	public void setAddr(java.lang.String addr) {
		set("addr", addr);
	}

	public java.lang.String getAddr() {
		return get("addr");
	}

	public void setQq(java.lang.String qq) {
		set("qq", qq);
	}

	public java.lang.String getQq() {
		return get("qq");
	}

	public void setMail(java.lang.String mail) {
		set("mail", mail);
	}

	public java.lang.String getMail() {
		return get("mail");
	}

	public void setWxId(java.lang.String wxId) {
		set("wx_id", wxId);
	}

	public java.lang.String getWxId() {
		return get("wx_id");
	}

	public void setRealName(java.lang.String realName) {
		set("real_name", realName);
	}

	public java.lang.String getRealName() {
		return get("real_name");
	}

	public void setChooseNum(java.lang.Integer chooseNum) {
		set("choose_num", chooseNum);
	}

	public java.lang.Integer getChooseNum() {
		return get("choose_num");
	}

	public void setIdentity(java.lang.String identity) {
		set("identity", identity);
	}

	public java.lang.String getIdentity() {
		return get("identity");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setState(java.lang.String state) {
		set("state", state);
	}

	public java.lang.String getState() {
		return get("state");
	}

	public void setNotes(java.lang.String notes) {
		set("notes", notes);
	}

	public java.lang.String getNotes() {
		return get("notes");
	}

	public void setNoWeeklyReportTimes(java.lang.Integer noWeeklyReportTimes) {
		set("no_weekly_report_times", noWeeklyReportTimes);
	}

	public java.lang.Integer getNoWeeklyReportTimes() {
		return get("no_weekly_report_times");
	}

	public void setWeeklyReportPower(java.lang.Boolean weeklyReportPower) {
		set("weekly_report_power", weeklyReportPower);
	}

	public java.lang.Boolean getWeeklyReportPower() {
		return get("weekly_report_power");
	}

}
