package com.znblog.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseZnLessonsPlan<M extends BaseZnLessonsPlan<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setLessonName(java.lang.String lessonName) {
		set("lesson_name", lessonName);
	}

	public java.lang.String getLessonName() {
		return get("lesson_name");
	}

	public void setLessonTitle(java.lang.String lessonTitle) {
		set("lesson_title", lessonTitle);
	}

	public java.lang.String getLessonTitle() {
		return get("lesson_title");
	}

	public void setLessonDes(java.lang.String lessonDes) {
		set("lesson_des", lessonDes);
	}

	public java.lang.String getLessonDes() {
		return get("lesson_des");
	}

	public void setLessonTime(java.util.Date lessonTime) {
		set("lesson_time", lessonTime);
	}

	public java.util.Date getLessonTime() {
		return get("lesson_time");
	}

	public void setLessonTeacher(java.lang.String lessonTeacher) {
		set("lesson_teacher", lessonTeacher);
	}

	public java.lang.String getLessonTeacher() {
		return get("lesson_teacher");
	}

	public void setLessonGrade(java.lang.String lessonGrade) {
		set("lesson_grade", lessonGrade);
	}

	public java.lang.String getLessonGrade() {
		return get("lesson_grade");
	}

	public void setLessonScore(java.lang.Float lessonScore) {
		set("lesson_score", lessonScore);
	}

	public java.lang.Float getLessonScore() {
		return get("lesson_score");
	}

	public void setLessonPlace(java.lang.String lessonPlace) {
		set("lesson_place", lessonPlace);
	}

	public java.lang.String getLessonPlace() {
		return get("lesson_place");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setState(java.lang.String state) {
		set("state", state);
	}

	public java.lang.String getState() {
		return get("state");
	}

	public void setNotes(java.lang.String notes) {
		set("notes", notes);
	}

	public java.lang.String getNotes() {
		return get("notes");
	}

}
