package com.znblog.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseZnUserBase<M extends BaseZnUserBase<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setUserName(java.lang.String userName) {
		set("userName", userName);
	}

	public java.lang.String getUserName() {
		return get("userName");
	}

	public void setPassword(java.lang.String password) {
		set("password", password);
	}

	public java.lang.String getPassword() {
		return get("password");
	}

	public void setNickName(java.lang.String nickName) {
		set("nickName", nickName);
	}

	public java.lang.String getNickName() {
		return get("nickName");
	}

	public void setSex(java.lang.Boolean sex) {
		set("sex", sex);
	}

	public java.lang.Boolean getSex() {
		return get("sex");
	}

	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}

	public java.lang.String getPhone() {
		return get("phone");
	}

	public void setQq(java.lang.String qq) {
		set("qq", qq);
	}

	public java.lang.String getQq() {
		return get("qq");
	}

	public void setEmail(java.lang.String email) {
		set("email", email);
	}

	public java.lang.String getEmail() {
		return get("email");
	}

	public void setImgUrl(java.lang.String imgUrl) {
		set("imgUrl", imgUrl);
	}

	public java.lang.String getImgUrl() {
		return get("imgUrl");
	}

	public void setPermission(java.lang.Long permission) {
		set("permission", permission);
	}

	public java.lang.Long getPermission() {
		return get("permission");
	}

	public void setLoginTime(java.util.Date loginTime) {
		set("loginTime", loginTime);
	}

	public java.util.Date getLoginTime() {
		return get("loginTime");
	}

	public void setLoginIp(java.lang.String loginIp) {
		set("loginIp", loginIp);
	}

	public java.lang.String getLoginIp() {
		return get("loginIp");
	}

	public void setLastLoginTime(java.util.Date lastLoginTime) {
		set("lastLoginTime", lastLoginTime);
	}

	public java.util.Date getLastLoginTime() {
		return get("lastLoginTime");
	}

	public void setLastLoginIp(java.lang.String lastLoginIp) {
		set("lastLoginIp", lastLoginIp);
	}

	public java.lang.String getLastLoginIp() {
		return get("lastLoginIp");
	}

	public void setGMTCreat(java.util.Date GMTCreat) {
		set("GMTCreat", GMTCreat);
	}

	public java.util.Date getGMTCreat() {
		return get("GMTCreat");
	}

	public void setGMTExpire(java.util.Date GMTExpire) {
		set("GMTExpire", GMTExpire);
	}

	public java.util.Date getGMTExpire() {
		return get("GMTExpire");
	}

	public void setNotes(java.lang.String notes) {
		set("notes", notes);
	}

	public java.lang.String getNotes() {
		return get("notes");
	}

}
